version: '3.9'

services:
  admin:
    build: .
    container_name: admin-interface
    env_file:
      - admin-interface.env
    ports:
      - "80:80"
      - "25565:25565"
    volumes:
      - ./server:/server